#!/bin/sh
# scripts/bump-build.sh — give this build a number newer than the last one.
#
# Writes CURRENT_PROJECT_VERSION into Config/BuildNumber.xcconfig, which
# Config/Version.xcconfig optionally includes and .gitignore excludes, so a
# bump never shows up as a working-tree change.
#
# The number is the current Unix time in seconds. Two properties matter:
#
#   - It only ever increases, so every install is unambiguously newer than the
#     one before it. That is the whole point — watchOS pushes an updated watch
#     app to the Watch only when it can see that the phone holds a newer build,
#     and the app previously carried no build number at all.
#   - It stays under 4294967295, the largest value Apple accepts in a build
#     number component, until 2106. A YYYYMMDDHHMMSS stamp would read more
#     nicely but crosses that ceiling immediately and would be rejected on
#     submission.
#
# Both targets read the one generated value, because a watch app and its
# companion iOS app must carry identical version and build numbers.

set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/Config/BuildNumber.xcconfig"
build=$(date +%s)

cat > "$out" <<EOF
// Generated by scripts/bump-build.sh — do not edit, and do not commit.
CURRENT_PROJECT_VERSION = $build
EOF

echo "build number: $build"
